#Run a job in a container.

on: [push]

jobs:
  hello_world_job:
    runs-on: ismajniah/democoursera:v0
    name: A job to say hello
    steps:
      - uses: actions/checkout@v3
      - name: Hello world action step
        id: hello
        uses: ./.github/actions/hello-world-myaction/
        with:
          who-to-greet: 'isma'
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
