#Run a job in a container.

on: [push]


name: container

jobs:
  node-docker:
    runs-on: ubuntu-latest
    container:
      image: node:latest
    steps:
         - name: Log the node version
           run: |
             node -v
             cat /etc/os-release  
