#Run a job in a container.

on: [push]


name: container

jobs:
  node-docker:
    runs-on: ubuntu:latest
    container:
      image: ubuntu:latest
      env:
        NODE_ENV: development
      ports:
        - 80
    steps:
         - name: Log the node version
           run: |
             ls
          
